# Generated by Django 5.0 on 2024-01-24 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=256, unique=True)),
                ('malumoti', models.TextField(blank=True)),
                ('rasmi', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismingiz', models.CharField(max_length=100, unique=True)),
                ('nomi', models.CharField(max_length=500, unique=True)),
                ('malumoti', models.TextField(blank=True, max_length=500)),
                ('narxi', models.IntegerField()),
                ('rasmi', models.ImageField(upload_to='photoes/products')),
                ('ulanish', models.CharField(max_length=100, unique=True)),
                ('Turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
